### ISSUE TITLE
Errors now with recent build of unity

### ISSUE THREAD

**Issue by clickmatch** [judah4/HSV-Color-Picker-Unity#10]
From the patch notes:
UI- Added: void LayoutComplete(); and void GraphicUpdateComplete(); to ICanvasElement. These callbacks are issued when the referenced canvas events are completed. You will need to add these to any custom components that use this interface.

Errors we get are:
Assets/HSVPicker/BoxSlider.cs(9,22): error CS0738: `UnityEngine.UI.BoxSlider' does not implement interface member`UnityEngine.UI.ICanvasElement.LayoutComplete()' and the best implementing candidate `UnityEngine.UI.BoxSlider.Rebuild(UnityEngine.UI.CanvasUpdate)' return type`void' does not match interface member return type `void'

Ok, so both voids but.. wait, what?

and

Assets/HSVPicker/BoxSlider.cs(9,22): error CS0535: `UnityEngine.UI.BoxSlider' does not implement interface member`UnityEngine.UI.ICanvasElement.GraphicUpdateComplete()'

I tried putting in empty voids just to satisfy the error monster and it was still hungry.

**Comment by judah4** [comment]
Latest update must have added more interface members that the BoxSlider does not implement yet.  All you have to do is add in BoxSlider.cs to fix it I think
```public void GraphicUpdateComplete() {}

public void LayoutComplete() {}```

**Comment by clickmatch** [comment]
Yes I added:
        public virtual void LayoutComplete(){}
        public virtual void GraphicUpdateComplete() { }


And now I get:
NullReferenceException: Object reference not set to an instance of an object
UnityEngine.UI.Graphic.OnRebuildRequested () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Graphic.cs:454)
UnityEngine.UI.GraphicRebuildTracker.OnRebuildRequested () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/GraphicRebuildTracker.cs:33)
UnityEngine.CanvasRenderer.RequestRefresh () (at C:/buildslave/unity/build/artifacts/generated/common/modules/CanvasRendererBindings.gen.cs:332)

So that's a little less straightforward for me.

**Comment by clickmatch** [comment]
Ok, your versions worked.. not too familiar with the virtual keyword...

**Comment by judah4** [comment]
Oh, hmm.  I wouldn't have thought that the virtual would make a difference.

Sorry,  I haven't been really managing this project since I've been working on other things.

**Comment by clickmatch** [comment]
Hey it's working again, so I'm happy. Best picker I've found, thanks for
that

**Comment by jeffweiz** [comment]
Thanks guys, that worked for me too.

**Comment by judah4** [comment]
Fixed in v2
