### ISSUE TITLE
Inverted HSV color

### ISSUE THREAD

**Issue by BeppiMenozzi** [judah4/HSV-Color-Picker-Unity#11]
Thanks for the fantastic picker!
I tried to fix this issue myself but couldn't get a clue.
The HSV bar, differently from what is displayed on your images, is inverted. Contains red, magenta, blue and so on from top to down. When the slider is put on - say - magenta, that's the color after red from top to down, the color selected is actually yellow, that is the color after red from bottom up.
![snap14](https://cloud.githubusercontent.com/assets/15621696/10898783/6aacee36-81ce-11e5-9be6-96299092e426.png)
Thanks in advance! :)

**Comment by judah4** [comment]
Should be fixed in v2
