### ISSUE TITLE
vestigial ColorPresets.cs

### ISSUE THREAD

**Issue by yosun** [judah4/HSV-Color-Picker-Unity#17]
why is there an additional identical copy of ColorPresets.cs outside of Assets folder?

https://github.com/judah4/HSV-Color-Picker-Unity/blob/master/ColorPresets.cs

**Comment by judah4** [comment]
An out of date preview

**Comment by tjohn93** [comment]
Has this been fixed?

**Comment by judah4** [comment]
No, it's still out there in the root of the folder

**Comment by judah4** [comment]
Removed it finally
