### ISSUE TITLE
Color Picker Prefab - Unity

### ISSUE THREAD

**Issue by tjohn93** [judah4/HSV-Color-Picker-Unity#18]
Will this work with a touch script?

**Comment by judah4** [comment]
It should, haven't tested it though

**Comment by tjohn93** [comment]
I would have to work with the ColorPreset.cs to make it function properly, correct?

**Comment by judah4** [comment]
If it's not working right, I guess? It's just unity ui stuff so it should work for touch controls just fine

**Comment by tjohn93** [comment]
Thanks.
