### ISSUE TITLE
Round version?

### ISSUE THREAD

**Issue by craftercis** [judah4/HSV-Color-Picker-Unity#21]
How can I make a roud version of this? So it fits in here?

![color_picker](https://user-images.githubusercontent.com/24845278/47681482-e3b50180-dbc9-11e8-9d98-9fbd1d8591fc.png)

**Comment by judah4** [comment]
You can move around the UI parts so I don't see why not. It probably wont fit properly though is my guess

**Comment by craftercis** [comment]
Hmm I need a version where I can set it to a gameobject and not specefic in de UI tab. Is this possible?

**Comment by judah4** [comment]
In the example scene one of the color pickers is in worldspace. It still needs to be attached to a canvas but that canvas can be placed in the world.
