### ISSUE TITLE
ColorBox is black on Android Device

### ISSUE THREAD

**Issue by BillyMartin1964** [judah4/HSV-Color-Picker-Unity#23]
The ColorBox changes the colors on the game objects fine, but the ColorBox doesn't update and stays black all of the time.

**Comment by judah4** [comment]
Could be an issue with the compute shader. If you can roll the changes back to check that would be helpful

**Comment by BillyMartin1964** [comment]
Roll what changes back? I just dragged the prefab in and added the code you had on this site. Is there something more to do?

I also tried to use you scene but got the same results.

**Comment by judah4** [comment]
Oh sorry, I mean with git to a previous point in history before the last pull request. I'll have to look at it later otherwise

**Comment by BillyMartin1964** [comment]
Okay. Please let me know. I like the code otherwise.

**Comment by BillyMartin1964** [comment]
Anything new on this?

**Comment by judah4** [comment]
Sorry, haven't had time to check on it yet.

**Comment by BillyMartin1964** [comment]
I just can't understand why it works when I hit the play button on the PC but not when I build it on the android device. Is there some code I need for the android build?

**Comment by BillyMartin1964** [comment]
@judah4 , I'm at the point of needing to publish my app. could you please take a few minutes and look at the color picker box and find out why it's black in android apps?

**Comment by judah4** [comment]
Download this branch if you need it now. https://github.com/judah4/HSV-Color-Picker-Unity/tree/PreComputeShader

**Comment by BillyMartin1964** [comment]
Works like a champ! Thank you so much, @judah4 !
