### ISSUE TITLE
TextMeshPro Option

### ISSUE THREAD

**Issue by LightningAAA** [judah4/HSV-Color-Picker-Unity#28]
It would be really nice if this color picker had a TMPro option/version (or just make it the default)

**Comment by judah4** [comment]
Good idea! TMPro should be made the default.

**Comment by MatchaJoeJoe** [comment]
So I did this with one of the projects I'm working on and decided to fork the repo and push my changes to the fork. Here are the changes I made, not sure if you want to merge this with the original master
[https://github.com/judah4/HSV-Color-Picker-Unity/compare/master...MatchaJoeJoe:master](https://github.com/judah4/HSV-Color-Picker-Unity/compare/master...MatchaJoeJoe:master)

**Comment by judah4** [comment]
There's a lot of maintenance I need to do that I haven't gotten to. Go ahead and make a pull request if all you did was swap to TMPro

**Comment by MatchaJoeJoe** [comment]
Ok, will do

**Comment by judah4** [comment]
TextMeshPro is now used.
