### ISSUE TITLE
The generated texture for the color box should have it's texture wrap mode set to clamp

### ISSUE THREAD

**Issue by LightningAAA** [judah4/HSV-Color-Picker-Unity#29]
I'm not sure exactly why sometimes this happens and sometimes it doesn't, but in my current project there's been an issue where there's been an annoying 1 pixel wide border around the color box (probably something to do with the scaling of the color picker).
![colorbox](https://user-images.githubusercontent.com/57412552/79613849-988ff680-80bc-11ea-8c05-3cd72596ecb2.jpg)
This issue wasn't with the shader itself, but with the raw image component wrapping the generated texture weird.
I fixed this by (in the SVBoxSlider.cs) making a public variable for which texture wrap mode to use, defaulting it to clamp, and setting the generated textures to use that wrap mode.
I don't know if there's a better way to do that, but it fixed the problem (and it seems to me like it should be made the default for the generated color box texture).

**Comment by judah4** [comment]
Fixed in v3.0.0
