### ISSUE TITLE
CSharp Files are missing namespace

### ISSUE THREAD

**Issue by Strepto** [judah4/HSV-Color-Picker-Unity#32]
Hi, nice package :)

In the latest release none of the `.cs` classes in this package has any namespaces. This makes it hard to add into a project as a UPM, as I cannot override / hard code a namespace for conflicting files. 

Consider adding namespace to all CS files, to make it non conflicting. 

I could add a pullrequest for this if I knew what namespace you wanted to use.

**Comment by judah4** [comment]
The current master branch has namespace HSVPicker now on all classes. An actual packaged release will be out sometime soon.

**Comment by Strepto** [comment]
Great! Thanks, closing this issue then.
