### ISSUE TITLE
Type or namespace ColorChangedEvent/HSVChanged Event could not be found

### ISSUE THREAD

**Issue by finndawg73** [judah4/HSV-Color-Picker-Unity#39]
Hi.  Using Unity 2020.2.0b2.3094:

Assets/HSVPicker/UI/ColorPicker.cs(18,16): error CS0246: The type or namespace name 'ColorChangedEvent' could not be found (are you missing a using directive or an assembly reference)?

Assets/HSVPicker/UI/ColorPicker.cs(19,16): error CS0246: The type or namespace name 'HSVChangedEvent' could not be found (are you missing a using directive or an assembly reference)?

Thanks!
<img width="1269" alt="HSVPickerError" src="https://user-images.githubusercontent.com/75796675/101788386-0797e080-3ace-11eb-9efa-213abad25607.png">

**Comment by pccom1370** [comment]
Version : Unity 2020.2.2f1
Unity Package Version : Color Picker 3.0.1

1. Import Package
2. Edit "HSVPicker.asmdef"
- Add Use GUIDs > UnityUIExtensions
- ![image](https://user-images.githubusercontent.com/3183770/106562602-dc7dba80-656d-11eb-9415-3d5effe2c3cb.png)
3. Each Error Script To Add "using UnityEngine.UI.Extensions.ColorPicker;"
- ![image](https://user-images.githubusercontent.com/3183770/106562636-eb646d00-656d-11eb-969d-824908373da1.png)
