### ISSUE TITLE
Errors on package import

### ISSUE THREAD

**Issue by DJBURBZ360** [judah4/HSV-Color-Picker-Unity#41]
Prefab errors
• Prefab's parent is missing a lot of script/component references
• Input field in prefab is not using TMPro causing reference errors

HSVPicker.asmdef Error
• Missing assembly reference to TMPro causing it not to work

**Comment by judah4** [comment]
What version of Unity and do you have textmesh pro in your project?

**Comment by DJBURBZ360** [comment]
I'm using 2018.3.14f1, and yes, I have both the essentials and examples in the project.

**Comment by judah4** [comment]
Looks like it's an issue with 2018. The current branch would have to be backported to 2018 to fix.

**Comment by judah4** [comment]
I was able to get it working again, check out branch unity2018.3 for the source. It's missing the TextMeshPro upgrade but all the other fixes are there.

 Going forward we'll stay on the supported LTS version with 2019.4 until that is no longer supported by Unity.
[HSVColorPicker2018-3.0.1.zip](https://github.com/judah4/HSV-Color-Picker-Unity/files/5767130/HSVColorPicker2018-3.0.1.zip)

**Comment by giovannibedetti** [comment]
Tried importing the package with UPM, then downloaded the .unitypackage, same errors:
`Assets\HSVPicker\UI\ColorPicker.cs(18,16): error CS0246: The type or namespace name 'ColorChangedEvent' could not be found`
`Assets\HSVPicker\UI\ColorPicker.cs(19,16): error CS0246: The type or namespace name 'HSVChangedEvent' could not be found`
looks great btw! very curious to try this out!
Is there something I can do to make it work?

**Comment by judah4** [comment]
> 

What version of Unity are you using?

When you look at the folder do you see these files under events?
![image](https://user-images.githubusercontent.com/7527244/144097654-cd7eb895-3253-4048-aaed-3212304d7179.png)

**Comment by giovannibedetti** [comment]
I'm on Unity 2020.3.16f1.
I just tried reimporting the package again, and it's my fault, because the package is already present inside the UnityUIExtensions, which I'm using, so I had errors on import which deleted the scripts from the folder, and the references broke. I didn't notice that I already had your color picker inside UnityUIExtensions!
All good! 
Sorry for the false flag!
