### ISSUE TITLE
Suggestion: Regenerate texture

### ISSUE THREAD

**Issue by sa20001** [judah4/HSV-Color-Picker-Unity#43]
Hi, I am trying to change the BoxSlider color, but after I have disabled the colorPicker, changed the color and then enabled the Color Picker the texture does not regenerate. It remains the same of the last color chosen.
Here the pic:
![image](https://user-images.githubusercontent.com/25508578/106391264-c1377180-63ec-11eb-9786-86348f724b23.png)

Previously I choose the green color, then disable the ColorPicker, and choose the purple color and at the end enable the ColorPicker. As can you see the texture is not generated.

But if I change the color afterwards  the texture is correctly generated. If I understand correctly my problem is due this part of code from SVBoxSlider:
```
  private void OnEnable()
        {
            if (Application.isPlaying && picker != null)
            {
                slider.onValueChanged.AddListener(SliderChanged);
                picker.onHSVChanged.AddListener(HSVChanged);
            }
        }
```
that generate the texture after that the color has been changed. But in my case I have changed the code before the listener is active.

I have solved the problem adding `RegenerateSVTexture();` at the end.

**Comment by judah4** [comment]
This was solved with #49
