### ISSUE TITLE
Color Box doesn't update if you assign a colour via script

### ISSUE THREAD

**Issue by PyreticDev** [judah4/HSV-Color-Picker-Unity#47]
This is what it looks like when you use picker.AssignColor(Color) or picker.CurrentColor = Color
![image](https://user-images.githubusercontent.com/80097192/132674803-378d4ae3-d2d0-414a-81c3-58632cde6ec2.png)
No matter what you do, the greyed out colour box will not update unless you click the input field with the hex code.
And this is what it looks like without these lines of code:
![image](https://user-images.githubusercontent.com/80097192/132674922-fde4d03f-1dca-4c01-89b4-0b022ede1528.png)

Is there a way to fix this?

**Comment by Nesh108** [comment]
Couldn't reproduce this. If I set the color picker to a color, it updates properly.

**Comment by blackjlc** [comment]
I had the same issue. It was because I removed all listeners on `ColorPicker.onValueChanged`. `ColorImage.ColorChanged` is subscribed to `ColorPicker.onValueChanged` during `ColorImage.Awake`. Maybe it's better to subscribe `ColorImage.ColorChanged` to another event that is not exposed.

**Comment by judah4** [comment]
I was able to reproduce then issue. It has to do with calling onValueChanged before setting the color internally when enabling the color picker or during first load.
