### ISSUE TITLE
HSVColour picker NOT USABLE in a Unity build (only works in editor) due to unneeded using

### ISSUE THREAD

**Issue by SimonDarksideJ** [judah4/HSV-Color-Picker-Unity#59]
Due to an unneeded using in the ColorSlider script (UnityEditor.Sprites), the package prevents builds to platforms.

https://github.com/judah4/HSV-Color-Picker-Unity/blob/0da638609b091d0678945df61f7987cb640bbd98/UI/ColorSlider.cs#L1

Removing this using enables a build to function.

P.S. I suggest getting the package to publish to OpenUPM and get version control rather than using a Git branch

**Comment by judah4** [comment]
Thanks for reporting! it will be fixed in 3.2.2
