### ISSUE TITLE
Fails when hidden

### ISSUE THREAD

**Issue by garmo** [judah4/HSV-Color-Picker-Unity#7]
I am trying to implement a car paint system. So, I hide the car paint window (where I have the color picker) in the main menu of my game. When I press a button to open (enable) the car paint window I get several errors.

Frist error: 
Texture has out of range width / height
UnityEngine.Texture2D:.ctor(Int32, Int32)
HSVUtil:GenerateHSVTexture(Int32, Int32) (at Assets/HSVPicker/UtilityScripts/HSVUtil.cs:190)
HSVPicker:init() (at Assets/HSVPicker/HSVPicker.cs:57)
HSVPicker:Awake() (at Assets/HSVPicker/HSVPicker.cs:43)

Second error:
UnityException: Failed to create texture because of invalid parameters.
UnityEngine.Texture2D..ctor (Int32 width, Int32 height)
HSVUtil.GenerateHSVTexture (Int32 width, Int32 height) (at Assets/HSVPicker/UtilityScripts/HSVUtil.cs:190)
HSVPicker.init () (at Assets/HSVPicker/HSVPicker.cs:57)
HSVPicker.Awake () (at Assets/HSVPicker/HSVPicker.cs:43)

**Comment by judah4** [comment]
No more errors when its hidden now.
