### ISSUE TITLE
Unity 5.1/5.2 Hex Text not updating/working

### ISSUE THREAD

**Issue by meachware** [judah4/HSV-Color-Picker-Unity#8]
I found that to get the hex text color to work I had to switch the public "Text" item over to be an actual "InputField" item and then access its .text component.
Examples:
        // Unity 5.1/2 needs an InputFiled vs grabbing the text component
	public InputField hexInput;

       public void ManipulateViaHex2RGB()
        {
	string hex = hexInput.text;
 ...

**Comment by judah4** [comment]
Fixed in v2
